# PersistentVolume for Django Backend
apiVersion: v1
kind: PersistentVolume
metadata:
  name: django-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/django"

---
# PersistentVolumeClaim for Django Backend
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-pvc
  namespace: backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: django-pv
