apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
  namespace: backend
type: Opaque
data:
  username: bXlzcWx1c2Vy  # Base64 encoded "mysqluser"
  password: bXlzcWxwYXNz  # Base64 encoded "mysqlpass"
