apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: backend-network-policy
  namespace: backend
spec:
  podSelector:
    matchLabels:
      app: django-mysql
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app: django-mysql
      ports:
        - protocol: TCP
          port: 8000  # Django
        - protocol: TCP
          port: 3306  # MySQL
  egress:
    - to:
      - podSelector:
          matchLabels:
            app: django-mysql
      ports:
        - protocol: TCP
          port: 8000
        - protocol: TCP
          port: 3306
