apiVersion: v1
kind: Service
metadata:
  name: react-nginx-service
  namespace: frontend
spec:
  selector:
    app: react-nginx
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: react
    port: 3000
    targetPort: 3000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: django-service
  namespace: backend
spec:
  selector:
    app: django-mysql
    component: django
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: backend
spec:
  selector:
    app: django-mysql
    component: mysql
  ports:
  - port: 3306
    targetPort: 3306
  type: ClusterIP
