apiVersion: v1
kind: Secret
metadata:
  name: django-secret
type: Opaque
data:
  DATABASE_PASSWORD: c2l4dHJhdmVsITA1MDUj  # Base64 인코딩된 "sixtravel!0505#"
  SECRET_KEY: ZGphbmdvLWluc2VjdXJlLTRpeV8zMWwhcTRyYnotIX5sIyF3bT1nd3B6Nz0zKmErMClrdXctcWZfcjlza3ZjOQ==  # Base64 인코딩된 "django-insecure-4iy_31l!q4-rbz-!^l#!wm=gwpz7=3*a+0)kuw-qf_r9skvc9"