# Role for Team Dev
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: team-dev-role
  namespace: frontend
rules:
- apiGroups: [""]
  resources: ["pods", "deployments", "daemonsets", "services", "horizontalpodautoscalers", "configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
# Role for Team Infra
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: team-infra-role
  namespace: backend
rules:
- apiGroups: [""]
  resources: ["nodes", "persistentvolumes", "persistentvolumeclaims", "services", "serviceaccounts"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
# Role for Team Sec
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: team-sec-role
  namespace: frontend
rules:
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "rolebindings"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["networkpolicies", "secrets", "configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
